image: python:3.6-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv/

stages:
  - test
  - publish

before_script:
  - python -V
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry install -vv

test:
  stage: test
  script:
    - poetry run pytest

publish:
  stage: publish
  script:
    - poetry publish --build --username $PYPI_USER --password $PYPI_PASSWORD
  only:
    - master
